### PR TITLE
Added asynchronous Backbone validation

### PR DESCRIPTION
**Pull request by fragsalat**
This version of Backbone validation is implemented using asynchronous validation callbacks.
So it's possible to do also validation with server / backend.
The implementation is backward compatible with all custom or default validation callbacks.
It's adding a new parameter to validation callbacks which contains a promise.
Simply resolve or reject the promise after your validation is done.

The usage is pretty simple. Just add the flag async to your validation.
If the flag is not set, the return value of the validator callback is used to resolve the validation.

Calling validator function

``` javascript
model.isValid(true, function valid() {}, function invalid(errors) {});
```

Usage of async validator in Model

``` javascript
/**
 * @see Backbone.Model.validation
 */
validation: {
    username: [{
        required: true,
        msg: 'Muss ausgefüllt werden'
    }, {
        usernameExists: true,
        async: true,
        msg: 'Der Name ist schon vergeben'
    }]
}
```

Here a sample implementation of my asynchronous callback to check if the inserted username already exists.

``` javascript
// Cache object for already requested user names
var usernames = {};
_.extend(Backbone.Validation.validators, {

    /**
     * Validator to check if a inserted username is already existing
     *
     * @param {string} value Input value
     * @param {string} attr Attribute name
     * @param {string} customValue
     * @param {Backbone.Model} model
     * @param {object} deferred Promise to resolve or reject
     */
    usernameExists: function usernameExists(value, attr, customValue, model, computed, deferred) {
        // If we have a username and it wasn't requested yet
        if (value && usernames[value] == undefined) {
            var ajax = new AJAXRequest({
                url: OSA.apiUrl('/api/usernameExists/' + encodeURIComponent(value)),
                method: 'get',
                success: function usernameExistsSuccess(response) {
                    // Cache username state
                    usernames[value] = response.data;
                    // Reject validation if user name exists
                    if (response.data) {
                        deferred.reject();
                    }
                    else {
                        deferred.resolve();
                    }
                }
            });
            ajax.send();
        }
        // The username was requested already and exists
        else if (value && usernames[value]) {
            deferred.reject();
        }
        // The value is empty or the username doesn't exist
        else {
            deferred.resolve();
        }
    }
});
```

### CODE REVIEW

**Comment by olhub** [comment]
+1

**Comment by aakhmerov** [comment]
why do we need something like that? :)

**Comment by fragsalat** [comment]
Because with the current implementation is no server validation possible.
The only way to do such things is to cache the server result, recall the validation and check the result.
This is not efficient because every time the whole model is validated.

**Comment by switchbert** [comment]
+1

**Comment by jaberu** [comment]
+1

**Comment by chiefGui** [comment]
> why do we need something like that? :)

Simplifying what @fragsalat said, sometimes we need to check if a user exists and in our current scenario is very boring to handle with this kind of validation — we have to dirt our code to be good to go.

Hence, @fragsalat, what an awesome implementation! A few weeks ago I started to developing this feature by myself but didn't go further for time issues.

 I'll be testing your functionality as soon as possible and then will be merging. And know what? Your feature will be releasing our very first major release — 1.0.0!

Thank very much so far. :beers: :+1:

**Comment by fragsalat** [comment]
@chiefGui I'll add some tests soon :)

**Comment by platinumazure** [comment]
How does this integrate with the Backbone `save` flow? Or calling `add` with `{validate: true}`? That Backbone code is synchronous and will laugh at the promises this will try to return. Basically the problem recurses and Backbone itself must be made asynchronous in order for this to work.

**Comment by fragsalat** [comment]
@chiefGui  I copied the existing tests and rewrote them for async version.

@platinumazure Your'e right, there is a different behavior now.
The `Backbone.Model.prototype.set` function is wrapped with a super call within the mixin to prevent setting of invalid values. This works good but you never will get an return value which indicates the success of your operation. Only for `Backbone.Model.prototype.save` i couldn't find a good solution yet without overriding the whole function. I'm open for suggestions :)

**Comment by fragsalat** [comment]
What's the status here? Will it be merged and when?

**Comment by platinumazure** [comment]
@fragsalat I can't imagine this is mergeable without accounting for the `save()` flow somehow. And that is going to suck, no question.

**Comment by fragsalat** [comment]
As you might see I overwrote the Model.set function. So it's possible to implement a callback for set and save to act on validation result.
Also you could deliver this as another version beside the default backbone-validation-amd.js

**Comment by mogarick** [comment]
Hi,
I've just found what appears to be a partial rewriting of functionality of this lib for async behavior. It's called [Async.Backbone.Validation](https://github.com/suevalov/async.backbone.validation). It was done by @suevalov

It looks it was derived from a 2013 versions of the lib.

Maybe it could help to merge both versions.

**Comment by jblotus** [comment]
+1 would really like to see this implemented.

**Comment by kinergy** [comment]
+1

**Comment by dbleyenda** [comment]
+1

**Comment by smilledge** [comment]
+1

**Comment by joebernard** [comment]
+1, not all validation can be implemented synchronously

**Comment by platinumazure** [comment]
That's all well and good, but _Backbone itself_ does not support
asynchronous validation. How do you expect this library to do so?

**Comment by joebernard** [comment]
@platinumazure  Isn't this a pull request?

**Comment by platinumazure** [comment]
I'm trying to say it won't work, at least not for all scenarios.

**Comment by misantronic** [comment]
+1
Are there any news if this will ever be a part of backbone.validation?

**Comment by fragsalat** [comment]
It looks not like it will be part.
I also don't maintain or update it anymore so feel free to fork my branch and update it :)

**Comment by bupy7** [comment]
+1

**Comment by Firanolfind** [comment]
+1 It could return Promise.

**Comment by fragsalat** [comment]
It is so old there was no "Promise" available. Only jQueries Deferred.

**Comment by Firanolfind** [comment]
I think it is time to move forward to ES6 using Promises.

**Comment by fragsalat** [comment]
I think Backbone isn't anymore the state of the art and therefore this will not happen from my side.

**Pull request closed without merging**
