### PR TITLE
Fix number validation to handle leading and trailing decimal

### LINKED ISSUE #103: Number pattern does not match decimals without a leading numeric value.
The current number pattern used by `Backbone.Validation` is `/^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/`.
Here are some tests which prove that it does not work as expected.

```
> var pattern = /^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/;
> "0.5".match(pattern);
["0.5"]

> ".5".match(pattern);
null
```

JavaScript treats these the same, however:

```
> Number("0.5");
0.5
> Number(".5");
.5
```

When binding to a View, such as a form, it's common for users to enter decimals without leading zeros. This current pattern does not sufficiently accomodate that, and puts the burden on developers to handle it.

### PR DESCRIPTION
**Pull request by shipstar**
`.01` and `123.` are both parsed by JavaScript as valid floats. These minor regex tweaks should allow backbone.validation to handle them as well.

Fixes #103.

### CODE REVIEW

**Comment by chiefGui** [comment]
Did you ran your tests to be sure things are working?

**Comment by shipstar** [comment]
I believe I ran the tests when I wrote the code, but it's been a while! I'll take a look tomorrow night to confirm.

**Comment by chiefGui** [comment]
Yes, it's been a while man — sorry for that.

I'll be waiting your test-check and if passes well, we'll be merging this fix.

Thank you so far! :+1:

**Comment by shipstar** [comment]
I think I got everything reconfigured correctly. Looks like tests are passing for me:

screen shot 2015-01-18 at 10 04 33 am

Let me know if there's anything else I can do to help out.

**Comment by platinumazure** [comment]
@shipstar From my taking a quick look, the tests look good. That said, it seems there are merge issues. @chiefGui Can collaborators handle merge conflicts or should the pull request be updated?

**Comment by chiefGui** [comment]
@platinumazure If you want to update this PR, just fork from https://github.com/shipstar/backbone.validation and then create a new PR, this way you can reuse @shipstar's work.

**Comment by shipstar** [comment]
Given that this PR is now 5 years old, I'm guessing it's far enough out of date that it shouldn't remain open. I'm going to close just to prune my PR list in GitHub, but I hope this was useful to someone else!

**Pull request closed without merging**
