### PR TITLE
Allow 'isValid' to check specific attributes even when no View is associated with the model.

### LINKED ISSUE #301: isValid only accepts a list of attributes for validation if the model is bound to a View
I recently attempted to use isValid as specified in the docs

> If you pass the name of an attribute or an array of names, you can check whether or not the attributes are valid:
> 
> ```
> // Check if name is valid 
> var isValid = model.isValid('name');
> // Check if name and age are valid
> var isValid = model.isValid(['name', 'age']);
> ```

I found it didn't work.  After digging in, I discovered that this was due to the array specific behavior being tied directly to the model having associatedViews.  You can see the relevant code here: https://github.com/thedersen/backbone.validation/blob/master/src/backbone-validation.js#L243

I'm opening a pull request separately to resolve this issue (#302), but wanted to open the issue first to document the problem.

### PR DESCRIPTION
**Pull request by benmccormick**
This should resolve #301.

Instead of looping over associated views and then looping over properties, I've modified the attribute validation code to loop over the attributes, and update the invalid attributes object first, then loop over the associated views to update them if they exist.  This maintains previous behavior and passes all tests, but works without an associated view.

### CODE REVIEW

**Comment by benmccormick** [comment]
Hey @chiefGui could you or someone else with commit privileges take a look at this?  Thanks so much

**Comment by benmccormick** [comment]
@thedersen @chiefGui is there anything I can do to get this moving?  Is there a current maintainer who I could discuss this PR with?

**Comment by fromthemills** [comment]
+1 Need this

**Comment by chiefGui** [comment]
Hey guys! Back to work tonight and I'll be versioning this. =)

**Comment by fromthemills** [comment]
Very much appreciated! Thanks @benmccormick for this fix.

**Comment by benmccormick** [comment]
@chiefGui great, thank you

**Comment by benmccormick** [comment]
@chiefGui any chance that we could get this moving?

**Comment by Growiel** [comment]
This should really be merged. It cost me so much time.

**Comment by jochakovsky** [comment]
@chiefGui Would you be able to take a look at this? Just ran into this issue in our project.

**Comment by e-burlaka-md** [comment]
hey @chiefGui  how is progress going?

**Comment by blikblum** [comment]
This is fixed in a fork i'm maintaining (tried contact this repository admins without luck): https://github.com/blikblum/backbone.validation

The updated package can be found at https://www.npmjs.com/package/backbone.validation

To use with node: npm install backbone.validation

**Pull request closed without merging**
