### PR TITLE
Support for Binding Multiple Views to same Model

### PR DESCRIPTION
**Pull request by RafaelCasuso**
Added support for binding multiple views to same model and being able to unbind each view separately from the model. This was a necessary step for me since I've designed a highly decoupled view structure for forms in my BackboneJs Application. That is based on composition of separated components (views, layouts) sharing a single Model that needs to be synchronized to their elements' values.

Without this support, when you try to bind several views that share the same model, only the last view gets actually bound resulting in a quite confusing behavior.

I've developed an approach of storing each associated view into an array attached to the model when the binding takes place, so they can be looped later when the validate method gets executed and the valid and invalid callbacks are run for each view marking the proper elements with its validated attributes.

This solves issues:
#140 
#227 

I've also included a suite of unit tests to the binding tests set.

I hope you find it as useful as it is to me. Feedback is more than welcome!

### CODE REVIEW

**Comment by chiefGui** [comment]
@RafaelCasuso Due to our latest release — v0.10.0 —, you have to update your tests. Could you?

**Comment by RafaelCasuso** [comment]
@chiefGui Sure thing. I'm on it.

**Comment by RafaelCasuso** [comment]
@chiefGui Everything should be ok now. Please let me know if any further change is needed.

**Comment by chiefGui** [comment]
Hey @RafaelCasuso. You're doing an amazing job! Tomorrow we'll be merging this. Thank you so far! :+1:

**Comment by chiefGui** [comment]
Thanks! :+1:

**Pull request merged**
