### PR TITLE
Use Object.prototype.hasOwnProperty instead

### PR DESCRIPTION
**Pull request by flintinatux**
Sometimes the `hasOwnProperty` property of an object is deleted or overridden by another library.  The best solution is to use `hasOwnProperty` from the `Object` prototype, as below ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#Example.3A_hasOwnProperty_as_a_property)):
```javascript
var foo = {
    hasOwnProperty: function() {
        return false;
    },
    bar: 'Here be dragons'
};

foo.hasOwnProperty('bar'); // always returns false

// Use another Object's hasOwnProperty and call it with 'this' set to foo
({}).hasOwnProperty.call(foo, 'bar'); // true

// It's also possible to use the hasOwnProperty property from the Object property for this purpose
Object.prototype.hasOwnProperty.call(foo, 'bar'); // true
```
I've run into this issue personally when using Backbone.Validation to validate [Bookshelf.js](http://bookshelfjs.org/) models in node.  It would throw `TypeError: undefined is not a function` when trying to `flatten` the model's attributes.  This change fixes it.

**NOTE:** I ran grunt, and all existing specs pass.  I didn't add any new specs, since this is more of a refactor than a bug-fix or new feature.

### CODE REVIEW

**Comment by platinumazure** [comment]
Might be worth adding a unit test to show the failure you described? That way the test suite would cover it should someone revert your proposed change.

**Comment by chiefGui** [comment]
To merge this, we need a unit test — can't go further without it.

Do you think you can do this for us, @flintinatux? I know, some time passed but this is still valid for our library. If you can't deal with this, please, just let us know then we can do the change by our own in another PR.

Thanks! :+1:

**Comment by flintinatux** [comment]
Thanks for the heads up.  Wish I could fix it, but our team isn't using
this anymore.  Feel free to make any changes that you need, or close it if
that works too.


--
Scott McCormack
cell:  (404) 862-1328
email:  mccormack.scott@gmail.com

**Comment by platinumazure** [comment]
Thanks @flintinatux.

@chiefGui let's close this and maybe open an issue; then one of us can open a new pull request as needed.

**Comment by blikblum** [comment]
I think that this change should not be applied. Annyone overriding a low level method like hasOwnProperty or using a library that does it should be aware of side effects.

**Comment by platinumazure** [comment]
@blikblum It's a common best practice to be aware of the possibility of overrides from other libraries and code defensively around them. [Even Underscore.js][1] uses this technique.

To be clear, we definitely don't want to override `Object.prototype.hasOwnProperty` here. We want to guard against someone else doing so.

  [1]: http://underscorejs.org/docs/underscore.html#section-7

**Comment by chiefGui** [comment]
@blikblum I am with @platinumazure. He pointed this thing out:

> We want to guard against someone else doing so.

And I'm d'accord. ;-)

**Comment by platinumazure** [comment]
@chiefGui At least we should consider using `_.has` instead of the naive `hasOwnProperty`?

**Pull request closed without merging**
