### PR TITLE
Expose formatting functions used for formatting error messages

### PR DESCRIPTION
**Pull request by aliebuck**
Exposes 2 methods:

``` js
Backbone.Validation.formatFunctions.formatLabel(attrName, model)
Backbone.Validation.formatFunctions.format()
```

Useful for writing method validators or custom validators which use default messages.

### CODE REVIEW

**Comment by platinumazure** [comment]
Rather than jump into this, I'd like to discuss if it makes sense to unify standard and custom error message processing first.

To me it would be awesome if messages were all (under the hood) functions which take similar arguments to the validators themselves. Maybe strings with numeric formatting markers could be special-cased to invocations of the format function.

Exposing `formatLabel` isn't a bad idea, though.

Just my 2¢.

**Comment by jacobbuck** [comment]
@platinumazure I agree. But this is just a short term fix until that's a reality.

**Comment by chiefGui** [comment]
What do you think guys about a Dictionary of messages?

**Comment by platinumazure** [comment]
@chiefGui What sort of thing are you thinking of? Care to write a quick example? (Pseudocode is fine)

**Comment by chiefGui** [comment]
@platinumazure you told:

> [...] unify standard and custom error message processing first [...]

For me, it makes lots of sense. Same interface: a dictionary. Something like `errorMessages.json` with `key`:`value` design.

If you stop and think about it, it turns globalization way easier.

Can you understand my point of view?

**Comment by platinumazure** [comment]
It's probably okay to release this as is, sure. I just wanted to make sure the concept was discussed.

Let's move further discussion to a new issue. I apologize for leading us down the rabbit hole in the first place.

**Comment by jacobbuck** [comment]
@thedersen any movement on this?

**Comment by aliebuck** [comment]
@thedersen _bump_

**Pull request closed without merging**
